name: native_oauth2
description: A Flutter plugin for authenticating with OAuth 2.0 providers using native platform APIs.
version: 0.0.2
repository: https://github.com/DYLERN/native_oauth2

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: za.drt.native_oauth2
        pluginClass: NativeOAuth2Plugin
      ios:
        pluginClass: NativeOAuth2Plugin
