name: native_oauth2
description: A library for performing oauth2 flows using native platform controls
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: za.drt.native_oauth2
        pluginClass: NativeOauth2Plugin
      ios:
        pluginClass: NativeOauth2Plugin
